server:
  port: 8081
dubbo:
  application:
    name: service    #服务名称
  registry:
    protocol: zookeeper     #注册中心的协议
    address: 192.168.1.114:2181 #注册中心的地址
  protocol:
    name: dubbo             #通信协议
    port: 20880             #通信端口
  monitor:
    protocol: registry      #连接监控中心

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3307/thirteen?characterEncoding=utf8
      username: root
      password: root
    master:
      url: jdbc:mysql://localhost:3306/thirteen?characterEncoding=utf8
      username: root
      password: root

  redis:
    #数据库索引
    database: 0
    host: 0.0.0.0
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000


mybatis:
  masterMapperLocations: classpath:com/rsq/wind/master/dao/mapper.xml
  slaveMapperLocations: classpath:com/rsq/wind/slave/dao/mapper.xml
