server:
  port: 8080
dubbo:
  application:
    name: web    #服务名称
  registry:
    protocol: zookeeper     #注册中心的协议
    address: 192.168.1.114:2181 #注册中心的地址
  monitor:
    protocol: registry      #连接监控中心
